=== dmrval/Life_Game-swing-and-Xml_courses-FX/src/main/xmlTask/Report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:mstns="http://www.w3.org/2001/XMLSchema-instance">

    <xs:simpleType name="allowed-task-types">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Theory"/>
            <xs:enumeration value="Practical"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="Theory">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AAA"/>
            <xs:enumeration value="BBB"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="University">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="StringValid" name="FullName"/>
                            <xs:element type="StringValid" name="City"/>
                            <xs:element type="Email" name="Email"/>
                            <xs:element type="DateFormat" name="TrainingStartDate"/>
                            <xs:element type="StringValid" name="SignedAcontract"/>
                            <xs:element name="Program">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ProgName"/>
                                        <xs:element name="ProgAuthor"/>
                                        <xs:element type="DateFormat" name="ProgCreationDate"/>
                                        <xs:element name="Course" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="CourceName" type="enumTypeCource">
                                                    </xs:element>
                                                    <xs:element type="StringValid" name="CourceAuthor"/>
                                                    <xs:element name="CourceCreationDate" type="DateFormat"/>
                                                    <xs:element name="Task" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="TaskName" type="enumTypeTask">
                                                                </xs:element>
                                                                <xs:element name="Assessment" type="type_assesment"
                                                                            nillable="true"/>



                                                                <xs:element name="Status" type="xs:string">

                                                                </xs:element>



                                                            </xs:sequence>
                                                            <xs:attribute type="xs:positiveInteger" name="hours"/>
                                                            <xs:attribute name="task-type" type="allowed-task-types"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:positiveInteger" name="id"/>
                                            </xs:complexType>
                                            <xs:unique name="uniqueTask">
                                                <xs:selector xpath="./*"/>
                                                <xs:field xpath="TaskName"/>
                                            </xs:unique>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                                <xs:unique name="uniqueCourceName">
                                    <xs:selector xpath="./*"/>
                                    <xs:field xpath="CourceName"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="type_assesment">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value=""/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="enumTypeCource">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Основы языка Java"/>
            <xs:enumeration value="Язык Java - расширенные возможности"/>
            <xs:enumeration value="Процесс производства программного обеспечения"/>
            <xs:enumeration value="Процесс разработки программного обеспечения"/>
            <xs:enumeration value="Overview of Eclipse IDE of Eclipse IDE 4"/>
            <xs:enumeration value="Язык XML"/>
            <xs:enumeration value="Язык XSLT и XPath"/>
            <xs:enumeration value="Технология Struts Framework"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="enumTypeTask">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Software development process. Development team and its structure"/>
            <xs:enumeration value="Mastering Microsoft Project"/>
            <xs:enumeration value="MS Project Practical Task"/>
            <xs:enumeration value="Learning the Java Language Basics"/>
            <xs:enumeration value="Practical Task"/>
            <xs:enumeration value="Overview of Eclipse IDE"/>
            <xs:enumeration value="Learning the Java Language advanced features"/>
            <xs:enumeration value="Learning XML Language"/>
            <xs:enumeration value="Equipment Stylesheets"/>
            <xs:enumeration value="Learning XSLT and XPath Basics"/>
            <xs:enumeration value="Struts Framework Fundamentals"/>
            <xs:enumeration value="Struts Framework Task"/>
            <xs:enumeration value="Java Message Service Task"/>
            <xs:enumeration value="Team Project"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="StringValid">
        <xs:restriction base="xs:string">
            <xs:maxLength value="700"/>
            <xs:minLength value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Email">
        <xs:restriction base="xs:string">
            <xs:pattern value="([\.a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(([a-zA-Z0-9_-])*\.([a-zA-Z0-9_-])+)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DateFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== dmrval/Life_Game-swing-and-Xml_courses-FX/src/main/xmlTask/StudentReport.xml
<?xml version="1.0" encoding="utf-8" ?>
<University xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
            xs:noNamespaceSchemaLocation="Report.xsd">
    <Student>
        <FullName>
            Alexander Sergeev

        </FullName>

        <City></City>
        <Email>AlexanderSergeev@gmai.com</Email>
        <TrainingStartDate>12.12.2015</TrainingStartDate>
        <SignedAcontract></SignedAcontract>
        <Program>
            <ProgName>
                Полная программа
            </ProgName>
            <ProgAuthor></ProgAuthor>
            <ProgCreationDate>12.12.2015</ProgCreationDate>
            <Course id="1">
                <CourceName>Overview of Eclipse IDE of Eclipse IDE 4</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="4">
                    <TaskName>Overview of Eclipse IDE</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="2">
                <CourceName>Основы языка Java</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>

                <Task hours="12">
                    <TaskName>Learning the Java Language Basics</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="4">
                    <TaskName>Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="3">
                <CourceName>Язык Java - расширенные возможности</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>

                <Task hours="17">

                    <TaskName>Learning the Java Language advanced features</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="16">
                    <TaskName>Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
            </Course>
            <Course id="4">
                <CourceName>Язык XML</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>

                <Task hours="6">
                    <TaskName>Learning XML Language</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
                <Task hours="8">
                    <TaskName>Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
            </Course>
            <Course id="5">
                <CourceName>Язык XSLT и XPath</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="14">
                    <TaskName>Learning XSLT and XPath Basics</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
                <Task hours="8">
                    <TaskName>Equipment Stylesheets</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="6">
                <CourceName>Технология Struts Framework</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="8">
                    <TaskName>Struts Framework Fundamentals</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
                <Task hours="40">
                    <TaskName>Struts Framework Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
                <Task hours="20">
                    <TaskName>Java Message Service Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
            </Course>
            <Course id="7">
                <CourceName>Процесс производства программного обеспечения</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="3">
                    <TaskName>Mastering Microsoft Project</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
                <Task hours="8">
                    <TaskName>MS Project Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
                <Task hours="12">
                    <TaskName>Software development process. Development team and its structure</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
            </Course>
            <Course id="8">
                <CourceName>Процесс разработки программного обеспечения</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="80">
                    <TaskName>Software development process. Development team and its structure</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>

                </Task>
            </Course>
        </Program>
    </Student>
    <Student>
        <FullName>
            Boris Romanov
        </FullName>
        <City></City>
        <Email>BorisRomanov@gmail.com</Email>
        <TrainingStartDate>12.12.2015</TrainingStartDate>
        <SignedAcontract></SignedAcontract>
        <Program>
            <ProgName>
                Полная программа
            </ProgName>
            <ProgAuthor></ProgAuthor>
            <ProgCreationDate>12.12.2015</ProgCreationDate>
            <Course id="1">
                <CourceName>Overview of Eclipse IDE of Eclipse IDE 4</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="4">
                    <TaskName>Overview of Eclipse IDE</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="2">
                <CourceName>Основы языка Java</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="12">
                    <TaskName>Learning the Java Language Basics</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="4">
                    <TaskName>Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="3">
                <CourceName>Язык Java - расширенные возможности</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="17">
                    <TaskName>Learning the Java Language advanced features</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="16">
                    <TaskName>Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="4">
                <CourceName>Язык XML</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="6">
                    <TaskName>Learning XML Language</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="8">
                    <TaskName>Practical Task</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="5">
                <CourceName>Язык XSLT и XPath</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="14">
                    <TaskName>Learning XSLT and XPath Basics</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="8">
                    <TaskName>Equipment Stylesheets</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
            </Course>
            <Course id="6">
                <CourceName>Технология Struts Framework</CourceName>
                <CourceAuthor></CourceAuthor>
                <CourceCreationDate>12.12.2015</CourceCreationDate>
                <Task hours="8">
                    <TaskName>Struts Framework Fundamentals</TaskName>
                    <Assessment></Assessment>
                    <Status></Status>
                </Task>
                <Task hours="40">
                    <TaskName>Struts Framework Task</TaskName>
                    <Assessment></Assessment>
